### ISSUE TITLE
Failed to initiate `BreakIterator` on windows

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skiko#103]
Modified demo app:

```
fun main(args: Array<String>) {
    val lineInstance = BreakIterator.makeLineInstance()
    repeat(1) {
        createWindow("window $it")
    }
}
```
crashed with:
```
Exception in thread "main" java.lang.RuntimeException: U_MISSING_RESOURCE_ERROR
	at org.jetbrains.skija.BreakIterator._nMake(Native Method)
	at org.jetbrains.skija.BreakIterator.makeLineInstance(BreakIterator.java:317)
	at org.jetbrains.skija.BreakIterator.makeLineInstance(BreakIterator.java:309)
	at SkijaInjectSample.AppKt.main(App.kt:18)
```

**Comment by igordmn** [comment]
This code works:
```
ParagraphBuilder(ParagraphStyle(), FontCollection())
BreakIterator.makeLineInstance()
```

Maybe skia/skija calls some initilizer for icu when we create ParagraphBuilder.

**Comment by tonsky** [comment]
Does this line gets executed? https://github.com/JetBrains/skija/blob/6dfd2eddc8c8e84c3828dd9ea373ff00d26ebce1/native/src/shaper/interop.cc#L181

**Comment by igordmn** [comment]
@olonho, can you look?

**Comment by olonho** [comment]
Shall be fixed with https://github.com/JetBrains/skiko/commit/e1c16426189530ff2d9aceea97b10d7f27a4a4db

**Comment by SergeevPavel** [comment]
Works for me. Thanks!
