### ISSUE TITLE
UnsatisfiedLinkError on Linux

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skiko#105]
Reproduced on: 
skiko: v0.2.27
Linux Ubuntu 18.04.5 LTS, version 5.4.0-1038-aws
JDK: amazon corretto-11
```
java.lang.UnsatisfiedLinkError: /mnt/agent/work/71b862de01f59e23/fleet/noria/kwinit/resources/libskiko-linux-x64.so: /mnt/agent/work/71b862de01f59e23/fleet/noria/kwinit/resources/libskiko-linux-x64.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEmc
  at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
  at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
  at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
  at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
  at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
  at java.base/java.lang.Runtime.load0(Runtime.java:768)
  at java.base/java.lang.System.load(System.java:1837)
  at org.jetbrains.skiko.Library.load(Library.kt:42)
  at org.jetbrains.skija.impl.Library$Companion.staticLoad(Library.kt:9)
  at org.jetbrains.skija.impl.Library.staticLoad(Library.kt)
  at org.jetbrains.skija.paragraph.ParagraphBuilder.<clinit>(ParagraphBuilder.java:9)
```

**Comment by olonho** [comment]
All undefined symbols in `libskiko-linux-x64.so` form 0.2.30 makes sense, but those
```
                 U _ZNKSt6locale4nameB5cxx11Ev
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKc
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEmc
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_eraseEmm
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm
                 U _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEOS4_
                 U _ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE7_M_syncEPcmm
                 U _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
                 U _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
                 U _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
```
When demangled they are:
```
                 U std::locale::name[abi:cxx11]() const
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
                 U std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)
                 U VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >
                 U vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >
                 U vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >
```

**Comment by olonho** [comment]
-D_GLIBCXX_USE_CXX11_ABI=0 could be helpful here.

**Comment by olonho** [comment]
@SergeevPavel please try https://github.com/JetBrains/skiko/releases/tag/v0.2.31, it includes build of Skia and Skiko with `-D_GLIBCXX_USE_CXX11_ABI=0`  and shall fix the problem.

**Comment by SergeevPavel** [comment]
Yes, it's fix the problem. Thank you!

**Comment by tonsky** [comment]
Looks like you are building Skiko on Ubuntu 14. In that case you should be using `...-gcc4.zip` version of skia-build, it has pre-C++-11 symbols

**Comment by olonho** [comment]
Problem is fixed, skia-build is no longer used.

**Comment by tonsky** [comment]
lol

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-105">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
