### ISSUE TITLE
Deadlock in MetalRedrawer

### ISSUE THREAD

**Issue by ignatov** [JetBrains/skiko#214]
Found one Java-level deadlock:
=============================
"DefaultDispatcher-worker-2":
  waiting to lock monitor 0x00007fe250048400 (object 0x00000007f0950b18, a java.awt.Component$AWTTreeLock),
  which is held by "AWT-EventQueue-0"
"AWT-EventQueue-0":
  waiting to lock monitor 0x00007fe23801f500 (object 0x00000007f18c8a38, a java.lang.Object),
  which is held by "DefaultDispatcher-worker-2"

Java stack information for the threads listed above:
===================================================
"DefaultDispatcher-worker-2":
	at java.awt.Component.getLocationOnScreen(java.desktop@11.0.12/Unknown Source)
	- waiting to lock <0x00000007f0950b18> (a java.awt.Component$AWTTreeLock)
	at javax.swing.SwingUtilities.convertPointToScreen(java.desktop@11.0.12/Unknown Source)
	at javax.swing.SwingUtilities.convertPoint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.SwingUtilities.convertPoint(java.desktop@11.0.12/Unknown Source)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.syncSize(MetalRedrawer.kt:97)
	at org.jetbrains.skiko.context.MetalContextHandler.initContext(MetalContextHandler.kt:18)
	at org.jetbrains.skiko.SkiaLayer.prepareDrawContext$skiko(SkiaLayer.kt:338)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.performDraw(MetalRedrawer.kt:89)
	- locked <0x00000007f18c8a38> (a java.lang.Object)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.access$performDraw(MetalRedrawer.kt:13)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$draw$2.invokeSuspend(MetalRedrawer.kt:77)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
"AWT-EventQueue-0":
	at org.jetbrains.skiko.redrawer.MetalRedrawer.performDraw(MetalRedrawer.kt:87)
	- waiting to lock <0x00000007f18c8a38> (a java.lang.Object)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.redrawImmediately(MetalRedrawer.kt:55)
	at org.jetbrains.skiko.SkiaLayer.paint(SkiaLayer.kt:212)
	at javax.swing.JComponent.paintChildren(java.desktop@11.0.12/Unknown Source)
	- locked <0x00000007f0950b18> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JLayeredPane.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JComponent.paintChildren(java.desktop@11.0.12/Unknown Source)
	- locked <0x00000007f0950b18> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JComponent.paintChildren(java.desktop@11.0.12/Unknown Source)
	- locked <0x00000007f0950b18> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JLayeredPane.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JComponent.paintChildren(java.desktop@11.0.12/Unknown Source)
	- locked <0x00000007f0950b18> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.paintToOffscreen(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JComponent.paint(java.desktop@11.0.12/Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(java.desktop@11.0.12/Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(java.desktop@11.0.12/Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(java.desktop@11.0.12/Unknown Source)
	at java.awt.Container.paint(java.desktop@11.0.12/Unknown Source)
	at java.awt.Window.paint(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager$4.run(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager$4.run(java.desktop@11.0.12/Unknown Source)
	at java.security.AccessController.doPrivileged(java.base@11.0.12/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.12/Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(java.desktop@11.0.12/Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(java.desktop@11.0.12/Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventQueue$4.run(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventQueue$4.run(java.desktop@11.0.12/Unknown Source)
	at java.security.AccessController.doPrivileged(java.base@11.0.12/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.12/Unknown Source)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.12/Unknown Source)

Found 1 deadlock.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-214">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
