### ISSUE TITLE
windows7 java.lang.RuntimeException: Can't wrap nullptr

### ISSUE THREAD

**Issue by yuhailong626** [JetBrains/skiko#31]
When I run [SkijaInjectSample](https://github.com/JetBrains/skiko/tree/master/samples/SkijaInjectSample) on windows, the following error is reported. Is there any solution?

System：windows7 x64 、Service Pack 1

Error message:
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
	at org.jetbrains.skija.impl.Native.<init>(Native.java:12)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:16)
	at org.jetbrains.skija.impl.Managed.<init>(Managed.java:12)
	at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:7)
	at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:21)
	at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
	at org.jetbrains.skiko.SkiaLayer.draw(SkiaWindow.kt:56)
	at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
	at org.jetbrains.skiko.HardwareLayer.display(HardwareLayer.kt:20)
	at org.jetbrains.skiko.HardwareLayer.paint(HardwareLayer.kt:16)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by yuhailong626** [comment]
It is same issue with [[Windows] - RuntimeException : Can't wrap nullptr](https://github.com/JetBrains/compose-jb/issues/125)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-31">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
