### ISSUE TITLE
ClassNotFoundException when start the application

### ISSUE THREAD

**Issue by IvanEFan** [JetBrains/skiko#424]
I have created a new kotlin/JVM project with IntelliJ IDEA with the `build.gradle.kts`:

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.6.0"
}

group = "me.ivanefan"
version = "1.0.0"

repositories {
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

val osName = System.getProperty("os.name")
val targetOs = when {
    osName == "Mac OS X" -> "macos"
    osName.startsWith("Win") -> "windows"
    osName.startsWith("Linux") -> "linux"
    else -> error("Unsupported OS: $osName")
}

val osArch = System.getProperty("os.arch")
var targetArch = when (osArch) {
    "x86_64", "amd64" -> "x64"
    "aarch64" -> "arm64"
    else -> error("Unsupported arch: $osArch")
}

val skikoVersion = "0.5.3"
val target = "${targetOs}-${targetArch}"
dependencies {
    testImplementation(kotlin("test"))
    implementation("org.jetbrains.skiko:skiko-jvm-runtime-$target:$skikoVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0-RC")
}

tasks.test {
    useJUnit()
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "1.8"
}
```

and I have copied the example in the README:

```kotlin
package me.ivanefan

import org.jetbrains.skia.Canvas
import org.jetbrains.skia.Color
import org.jetbrains.skia.Paint
import org.jetbrains.skiko.GenericSkikoView
import org.jetbrains.skiko.SkiaLayer
import org.jetbrains.skiko.SkikoView
import java.awt.Dimension
import javax.swing.JFrame
import javax.swing.SwingUtilities
import javax.swing.WindowConstants

fun main() {
    val skiaLayer = SkiaLayer()
    skiaLayer.skikoView = GenericSkikoView(skiaLayer, object : SkikoView {
        val paint = Paint().apply {
            color = Color.RED
        }
        override fun onRender(canvas: Canvas, width: Int, height: Int, nanoTime: Long) {
            canvas.clear(Color.CYAN)
            val ts = nanoTime / 5_000_000
            canvas.drawCircle( (ts % width).toFloat(), (ts % height).toFloat(), 20f, paint )
        }
    })
    SwingUtilities.invokeLater {
        val window = JFrame("Skiko example").apply {
            defaultCloseOperation = WindowConstants.EXIT_ON_CLOSE
            preferredSize = Dimension(800, 600)
        }
        skiaLayer.attachTo(window.contentPane)
        skiaLayer.needRedraw()
        window.pack()
        window.isVisible = true
    }
}
```

However, after I run the main function, I got this:

```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/coroutines/GlobalScope
	at org.jetbrains.skiko.FrameWatcher.start(FrameWatcher.kt:22)
	at org.jetbrains.skiko.Setup.init(Setup.kt:35)
	at org.jetbrains.skiko.Setup.init$default(Setup.kt:6)
	at org.jetbrains.skiko.Library.load(Library.kt:92)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.jvm.kt:34)
	at me.ivanefan.MainKt.main(main.kt:15)
	at me.ivanefan.MainKt.main(main.kt)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.GlobalScope
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 7 more

Process finished with exit code 1
```

after I add `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0-RC")` to the `dependencies` block in my `build.gradle.kts`, it still don't work:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: kotlinx/coroutines/swing/SwingDispatcherKt
	at org.jetbrains.skiko.redrawer.MetalRedrawer.<init>(MetalRedrawer.kt:32)
	at org.jetbrains.skiko.RenderFactory_jvmKt$makeDefaultRenderFactory$1.createRedrawer(RenderFactory.jvm.kt:29)
	at org.jetbrains.skiko.SkiaLayer.findNextWorkingRenderApi(SkiaLayer.jvm.kt:225)
	at org.jetbrains.skiko.SkiaLayer.init(SkiaLayer.jvm.kt:240)
	at org.jetbrains.skiko.SkiaLayer.checkInit(SkiaLayer.jvm.kt:94)
	at org.jetbrains.skiko.SkiaLayer._init_$lambda-0(SkiaLayer.jvm.kt:82)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6802)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.Component.addNotify(Component.java:7106)
	at java.desktop/java.awt.Canvas.addNotify(Canvas.java:104)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:733)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/java.awt.Window.addNotify(Window.java:786)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:490)
	at java.desktop/java.awt.Window.pack(Window.java:824)
	at me.ivanefan.MainKt.main$lambda-1(main.kt:33)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.swing.SwingDispatcherKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 39 more
```

Project JDK: `JDK 11.0.12 x86`

**Comment by olonho** [comment]
Because you need to use `org.jetbrains.kotlinx:kotlinx-coroutines-swing`.

**Comment by IvanEFan** [comment]
> Because you need to use `org.jetbrains.kotlinx:kotlinx-coroutines-swing`.

Oh, It works! Thanks so much.

Maybe it would be better to mark it in the README.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-424">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
