### ISSUE TITLE
Suddenly, I am starting to get this exception

### ISSUE THREAD

**Issue by igr** [JetBrains/skiko#490]
Everything worked yesterday.

```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.ref.PhantomReference.reachabilityFence(Ljava/lang/Object;)V
	at org.jetbrains.skia.impl.CleanableImpl.<init>(Managed.jvm.kt:75)
	at org.jetbrains.skia.impl.Cleaner.register(Managed.jvm.kt:140)
	at org.jetbrains.skia.impl.Managed.<init>(Managed.jvm.kt:52)
	at org.jetbrains.skia.impl.RefCnt.<init>(RefCnt.jvm.kt:6)
	at org.jetbrains.skia.Surface.<init>(Surface.kt:978)
	at org.jetbrains.skia.Surface$Companion.makeRasterN32Premul(Surface.kt:355)
```

**Comment by igr** [comment]
Ah, wrong Java, project went back to java8. Setting Java11 worked

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-490">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
