### ISSUE TITLE
Unknown arch i686 error

### ISSUE THREAD

**Issue by Octoate** [JetBrains/skiko#542]
Hi,
I am currently trying to build a small sample application for Android and included Skiko in it. When I start the application in the Android emulator (Pixel 4, API 30, Android 11.0, Google Play), I get the error "Unknown arch i686" with the stack trace below.
Shouldn't this architecture be the same like "x86_64" and "amd64"? If so, please add it to "hostArch" in the "properties.kt", to support it, too.

Regards,
Tim

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.skikoexample, PID: 11232
    java.lang.Error: Unknown arch i686
        at org.jetbrains.skiko.OsArch_jvmKt$hostArch$2.invoke(OsArch.jvm.kt:19)
        at org.jetbrains.skiko.OsArch_jvmKt$hostArch$2.invoke(OsArch.jvm.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.skiko.OsArch_jvmKt.getHostArch(OsArch.jvm.kt:14)
        at org.jetbrains.skiko.OsArch_jvmKt$hostId$2.invoke(OsArch.jvm.kt:24)
        at org.jetbrains.skiko.OsArch_jvmKt$hostId$2.invoke(OsArch.jvm.kt:23)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.skiko.OsArch_jvmKt.getHostId(OsArch.jvm.kt:23)
        at org.jetbrains.skiko.Library.findAndLoad(Library.kt:73)
        at org.jetbrains.skiko.Library.load(Library.kt:59)
        at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
        at org.jetbrains.skia.Surface.<clinit>(Surface.kt:533)
        at com.example.skikoexample.FirstFragment.onViewCreated(FirstFragment.kt:41)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Octoate** [comment]
My fault... not 64bit. Sorry :-).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-542">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
