### ISSUE TITLE
Rendering for low resolution black and white display

### ISSUE THREAD

**Issue by silabpm** [JetBrains/skiko#578]
Is there a way to tell a Surface to only have black and white color (no gray) and to disable anti-aliasing and subpixels?

**Comment by silabpm** [comment]
I found, that Paint has an AntiAlias option and Font a Subpixel option, but i cant find a way to edit both in a ParagraphBuilder.

**Comment by silabpm** [comment]
Thx [SergeevPavel](https://github.com/JetBrains/skiko/commits?author=SergeevPavel) the new method seems to have an issue on Android so:
```
No implementation found for void org.jetbrains.skia.paragraph.ParagraphStyleKt._nSetFontRastrSettings(long, int, int, boolean) (tried Java_org_jetbrains_skia_paragraph_ParagraphStyleKt__1nSetFontRastrSettings and Java_org_jetbrains_skia_paragraph_ParagraphStyleKt__1nSetFontRastrSettings__JIIZ)
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.UnsatisfiedLinkError: No implementation found for void org.jetbrains.skia.paragraph.ParagraphStyleKt._nSetFontRastrSettings(long, int, int, boolean) (tried Java_org_jetbrains_skia_paragraph_ParagraphStyleKt__1nSetFontRastrSettings and Java_org_jetbrains_skia_paragraph_ParagraphStyleKt__1nSetFontRastrSettings__JIIZ)
        at org.jetbrains.skia.paragraph.ParagraphStyleKt._nSetFontRastrSettings(Native Method)
        at org.jetbrains.skia.paragraph.ParagraphStyleKt.access$_nSetFontRastrSettings(ParagraphStyle.kt:1)
        at org.jetbrains.skia.paragraph.ParagraphStyle.setFontRastrSettings(ParagraphStyle.kt:188)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-578">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
