### ISSUE TITLE
Investigate Linux hangs in tests

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#629]
Sometimes we have tests on Linux hanging at[this line](https://github.com/JetBrains/skiko/blob/bd79451ac87dbd4107d7bc460a831b6369805a6f/skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxSoftwareRedrawer.kt#L26)

A temporary workaround is done [here](https://github.com/JetBrains/skiko/pull/628)

**Comment by dima-avdeev-jb** [comment]
I changed **inline fun lockLinuxDrawingSurface** to simple fun. And this is stacktrae of 2 blocking threads:

```
"DefaultDispatcher-worker-1" #61 daemon prio=5 os_prio=0 cpu=19.16ms elapsed=581.33s tid=0x00007fc450022800 nid=0x1b4a waiting on condition  [0x00007fc423c0d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x00000000e052f3c0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.11/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.11/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.11/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.11/ReentrantLock.java:267)
	at sun.awt.SunToolkit.awtLock(java.desktop@11.0.11/SunToolkit.java:195)
	at org.jetbrains.skiko.AWTKt.lockDrawingSurface(Native Method)
	at org.jetbrains.skiko.AWTKt.access$lockDrawingSurface(AWT.kt:1)
	at org.jetbrains.skiko.DrawingSurface.lock(AWT.kt:35)
	at org.jetbrains.skiko.AWTLinuxDrawingSurfaceKt.lockLinuxDrawingSurface(AWTLinuxDrawingSurface.kt:14)
	at org.jetbrains.skiko.AWTLinuxDrawingSurfaceKt.lockLinuxDrawingSurface(AWTLinuxDrawingSurface.kt:4)
	at org.jetbrains.skiko.DisplayKt.getDisplayRefreshRate(Display.kt:11)
	at org.jetbrains.skiko.HardwareLayerKt$FrameLimiter$2.invokeSuspend(HardwareLayer.kt:163)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

"AWT-EventQueue-0 @coroutine#381" #114 prio=6 os_prio=0 cpu=2417.81ms elapsed=576.13s tid=0x00007fc47d5ae800 nid=0x1b81 waiting on condition  [0x00007fc4131c6000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x00000000e1cc98e8> (a kotlinx.coroutines.BlockingCoroutine)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.11/LockSupport.java:234)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:88)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.jetbrains.skiko.redrawer.AbstractDirectSoftwareRedrawer.dispose(AbstractDirectSoftwareRedrawer.kt:56)
	at org.jetbrains.skiko.redrawer.LinuxSoftwareRedrawer.access$dispose$s659551382(LinuxSoftwareRedrawer.kt:5)
	at org.jetbrains.skiko.redrawer.LinuxSoftwareRedrawer$dispose$1.invoke(LinuxSoftwareRedrawer.kt:27)
	at org.jetbrains.skiko.redrawer.LinuxSoftwareRedrawer$dispose$1.invoke(LinuxSoftwareRedrawer.kt:26)
	at org.jetbrains.skiko.AWTLinuxDrawingSurfaceKt.lockLinuxDrawingSurface(AWTLinuxDrawingSurface.kt:6)
	at org.jetbrains.skiko.redrawer.LinuxSoftwareRedrawer.dispose(LinuxSoftwareRedrawer.kt:26)
	at org.jetbrains.skiko.SkiaLayer.dispose(SkiaLayer.awt.kt:330)
	at org.jetbrains.skiko.util.UiTestScope$UiTestWindow$1.dispose(UiTest.kt:50)
	at javax.swing.JFrame.processWindowEvent(java.desktop@11.0.11/JFrame.java:306)
	at java.awt.Window.processEvent(java.desktop@11.0.11/Window.java:2037)
	at java.awt.Component.dispatchEventImpl(java.desktop@11.0.11/Component.java:5011)
	at java.awt.Container.dispatchEventImpl(java.desktop@11.0.11/Container.java:2321)
	at java.awt.Window.dispatchEventImpl(java.desktop@11.0.11/Window.java:2772)
	at java.awt.Component.dispatchEvent(java.desktop@11.0.11/Component.java:4843)
	at org.jetbrains.skiko.SkiaLayerTestKt.close(SkiaLayerTest.kt:723)
	at org.jetbrains.skiko.SkiaLayerTestKt.access$close(SkiaLayerTest.kt:1)
	at org.jetbrains.skiko.SkiaLayerTest$stress test - open and paint immediately$1.invokeSuspend(SkiaLayerTest.kt:367)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.11/InvocationEvent.java:313)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.11/EventQueue.java:770)
	at java.awt.EventQueue$4.run(java.desktop@11.0.11/EventQueue.java:721)
	at java.awt.EventQueue$4.run(java.desktop@11.0.11/EventQueue.java:715)
	at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.11/ProtectionDomain.java:85)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.11/EventQueue.java:740)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.11/EventDispatchThread.java:203)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.11/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.11/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.11/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.11/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.11/EventDispatchThread.java:90)

```

**Comment by dima-avdeev-jb** [comment]
Full stacktrace:
[failed3-full.txt](https://github.com/JetBrains/skiko/files/10185856/failed3-full.txt)

**Comment by igordmn** [comment]
Fixed in https://github.com/JetBrains/skiko/pull/646

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-629">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
