### ISSUE TITLE
ArrayIndexOutOfBoundsException in ImageInfo in arm64 

### ISSUE THREAD

**Issue by silabpm** [JetBrains/skiko#679]
When reading an 1 bit per pixel .bmp with 
`Image.makeFromEncoded(inputStream.readAllBytes())`
there is an ArrayIndexOutOfBoundsException thrown when trying to work with that image (arm only):

`java.lang.ArrayIndexOutOfBoundsException: Index -1659921872 out of bounds for length 4
        at org.jetbrains.skia.ImageInfo.<init>(ImageInfo.kt:46)
        at org.jetbrains.skia.ImageInfo$Companion.createUsing(ImageInfo.kt:298)
        at org.jetbrains.skia.Image$imageInfo$1.invoke(Image.kt:159)
        at org.jetbrains.skia.Image$imageInfo$1.invoke(Image.kt:157)
        at org.jetbrains.skia.Actuals_jvmKt.commonSynchronized(Actuals.jvm.kt:6)
        at org.jetbrains.skia.Image.getImageInfo(Image.kt:157)
        at org.jetbrains.skia.IHasImageInfo$DefaultImpls.getWidth(IHasImageInfo.kt:15)
        at org.jetbrains.skia.Image.getWidth(Image.kt:6)`

ImageInfo.kt:46:
`ColorAlphaType.values()[alphaType],`

**Comment by pjBooms** [comment]
Can you provide a reproducer project (including 1 bit per pixel .bmp you try to read)?

**Comment by silabpm** [comment]
Seems to be gone in new version.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-679">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
