### ISSUE TITLE
Snapshot testing on Android

### ISSUE THREAD

**Issue by hbrtose** [JetBrains/skiko#760]
Hi, I'm trying to implement snapshot testing of my Skiko based project and when using Shot, Paparazzi and Testify I always come back to getting the same error when a screen is about to be opened in the emulator:

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN4sksg4NodeD2Ev" referenced by "/data/app/~~5EF6ptID-XiVTOy1p3z47g==/com.hubert.canvas.test-30dXbNG8KKjdhRBTiTkoyA==/base.apk!/lib/x86_64/libskiko-android-x64.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at org.jetbrains.skiko.Library.findAndLoad(Library.kt:78)
        at org.jetbrains.skiko.Library.load(Library.kt:59)
        at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
        at org.jetbrains.skia.paragraph.ParagraphStyle.<clinit>(ParagraphStyle.kt:17)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-760">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
