### ISSUE TITLE
[ERROR] SKIKO COULD NOT FOUND library libGL.so.1

### ISSUE THREAD

**Issue by ghost** [JetBrains/skiko#780]
I'm running Termux with xfce4 with compose-multiplaform-template and when I run ./gradlew run  I get this error 
```
> Task :desktopApp:run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/home/.skiko/664c862db42629565e1dd3eaaf7b5b1452f4b8472a7769a15f7e6b981ca36e1a/libskiko-linux-arm64.so: dlopen failed: library "libGL.so.1" not found: needed by /data/data/com.termux/files/home/.skiko/664c862db42629565e1dd3eaaf7b5b1452f4b8472a7769a15f7e6b981ca36e1a/libskiko-linux-arm64.so in namespace (default)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:751)
        at java.base/java.lang.System.load(System.java:1912)
        at org.jetbrains.skiko.Library.loadLibraryOrCopy(Library.kt:20)
        at org.jetbrains.skiko.Library.findAndLoad(Library.kt:113)
        at org.jetbrains.skiko.Library.load(Library.kt:59)
        at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
        at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:110)
        at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
        at MainKt.main(main.kt:4)
        at MainKt.main(main.kt)

FAILURE: Build failed with an exception.

```
I have libGL.so.1 in ```/data/data/com.termux/files/usr/lib/libGL.so.1``` 
I also have LD_LIBRARY_PATH to that lib folder
I also tried with copying libGL.so.1 to 
```/data/data/com.termux/files/home/.skiko/664c862db42629565e1dd3eaaf7b5b1452f4b8472a7769a15f7e6b981ca36e1a/``` folder

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-780">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
