### ISSUE TITLE
Pinch gesture on Android

### ISSUE THREAD

**Issue by hbrtose** [JetBrains/skiko#802]
I am trying to implement pinch zoom in a KMM app, and while it works well on iOS, there are issues on Android. As you can see on the screenshot, MotionEvent has 2 points, but event.x and event.y value that's passed down to onGestureEvent are just the first point, instead of an average of both. 

![image](https://github.com/JetBrains/skiko/assets/23407258/e313f9e5-30b4-4c4c-baef-d8466bc4673f)

Also when pinching on Android I noticed I receive both Pinch and Pan events, whereas on iOS I only get Pinch events.

**Comment by hbrtose** [comment]
Here's an example with Clocks demo edited to show the point where pinching is considered to happen and informing when panning is happening (even during a pinch)
https://github.com/hbrtose/skiko/blob/master/samples/SkiaAndroidSample/src/main/java/org/jetbrains/skiko/sample/Clocks.kt
Also, even with coroutines, kotlin and gradle plugin bumped to the newest versions, the app crashes on startup with any version of skiko above 0.7.77

```
 Failed to measure fs-verity, errno 1: /data/app/~~hV8Iwq5JcCjo_yTasxGG_A==/org.jetbrains.skiko.sample-2Bg_qermzNj0EQXJvojaQw==/base.apk
searching for layers in '/data/app/~~hV8Iwq5JcCjo_yTasxGG_A==/org.jetbrains.skiko.sample-2Bg_qermzNj0EQXJvojaQw==/lib/arm64'
searching for layers in '/data/app/~~hV8Iwq5JcCjo_yTasxGG_A==/org.jetbrains.skiko.sample-2Bg_qermzNj0EQXJvojaQw==/base.apk!/lib/arm64-v8a'
checking cmar_predictor for org.jetbrains.skiko.sample
Invalid ID 0x00000000.
Shutting down VM
FATAL EXCEPTION: main
Process: org.jetbrains.skiko.sample, PID: 1242
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN4sksg4NodeD2Ev" referenced by "/data/app/~~hV8Iwq5JcCjo_yTasxGG_A==/org.jetbrains.skiko.sample-2Bg_qermzNj0EQXJvojaQw==/base.apk!/lib/arm64-v8a/libskiko-android-arm64.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:78)
                                                                                                    	at org.jetbrains.skiko.Library.load(Library.kt:59)
                                                                                                    	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
                                                                                                    	at org.jetbrains.skia.paragraph.FontCollection.<clinit>(FontCollection.kt:11)
                                                                                                    	at org.jetbrains.skiko.sample.Clocks.<init>(Clocks.kt:25)
                                                                                                    	at org.jetbrains.skiko.sample.MainActivity.onCreate(MainActivity.kt:27)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8054)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8034)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by sgopi93** [comment]
Hi, Any update onthis.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-802">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
