### ISSUE TITLE
UnsupportedOperationException — The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by x80486** [JetBrains/skiko#839]
While testing an application that uses `Compose Multiplatform`, this exception is observed:

```shell
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Unknown Source)
	at java.desktop/java.awt.Desktop.browse(Unknown Source)
	at org.jetbrains.skiko.Actuals_awtKt.URIHandler_openUri(Actuals.awt.kt:44)
	at org.jetbrains.skiko.URIManager.openUri(Platform.kt:12)
	at chat.simplex.common.views.call.CallView_desktopKt.WebRTCController(CallView.desktop.kt:151)
	at chat.simplex.common.views.call.CallView_desktopKt.ActiveCallView(CallView.desktop.kt:48)
	at chat.simplex.common.AppKt.MainScreen(App.kt:163)
	at chat.simplex.common.AppKt$MainScreen$7.invoke(App.kt)
	at chat.simplex.common.AppKt$MainScreen$7.invoke(App.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2469)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2738)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3353)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3304)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:543)
	at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:178)
	at androidx.compose.ui.awt.ComposeBridge$skikoView$1$onRender$1.invoke(ComposeBridge.desktop.kt:177)
	at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:150)
	at androidx.compose.ui.awt.ComposeBridge.access$catchExceptions(ComposeBridge.desktop.kt:64)
	at androidx.compose.ui.awt.ComposeBridge$skikoView$1.onRender(ComposeBridge.desktop.kt:177)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:548)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.AbstractDirectSoftwareRedrawer$frameDispatcher$1.invokeSuspend(AbstractDirectSoftwareRedrawer.kt:25)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@7442a11f, androidx.compose.runtime.BroadcastFrameClock@659db4d, StandaloneCoroutine{Cancelling}@563ed3d6, FlushCoroutineDispatcher@fb5c024]
```

I checked the implementation of `src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt` and looks like the logic for `URIHandler_openUri` might not be up to date. I'm not versed in this library (or desktop-oriented applications) but looks like the problem is with the `Java` desktop integration, particularly in Linux. Probably the checks could be in this order:

1. GNOME + KDE (`gnome-open` / `kde-open`) — maybe even skip them altogether? :smile:
2. X / Wayland (`xdg-open`)
3. macOS (not sure what they use)
4. ...

Maybe `isDesktopSupported()` could be used before? You will definitely have more insight on this.

Let me know if you need anything else :wave:

**Comment by m-sasha** [comment]
Hi, is this on Linux? If so, it should already be fixed, but hasn't been released yet - see https://github.com/JetBrains/compose-multiplatform/issues/3583

**Comment by x80486** [comment]
Yes, it's `Linux`. I didn't notice there was another issue around this subject. Thanks for the info...I'll close this one! :wave:

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-839">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
