### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 'void org.jetbrains.skiko.OpenGLLibrary_jvmKt.loadOpenGLLibraryWindows()'

### ISSUE THREAD

**Issue by mahozad** [JetBrains/skiko#872]
OS: Windows 11

When updating skiko from `0.7.92` to `0.7.93`, my app fails to start with this exception:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.jetbrains.skiko.OpenGLLibrary_jvmKt.loadOpenGLLibraryWindows()'
	at org.jetbrains.skiko.OpenGLLibrary_jvmKt.loadOpenGLLibraryWindows(Native Method)
	at org.jetbrains.skiko.OpenGLLibrary_jvmKt.loadOpenGLLibrary(OpenGLLibrary.jvm.kt:16)
	at org.jetbrains.skiko.redrawer.WindowsOpenGLRedrawer.<init>(WindowsOpenGLRedrawer.kt:13)
	at org.jetbrains.skiko.Actuals_awtKt$makeDefaultRenderFactory$1.createRedrawer(Actuals.awt.kt:33)
	at org.jetbrains.skiko.SkiaLayer$redrawerManager$1.invoke(SkiaLayer.awt.kt:304)
	at org.jetbrains.skiko.SkiaLayer$redrawerManager$1.invoke(SkiaLayer.awt.kt:302)
	at org.jetbrains.skiko.redrawer.RedrawerManager.findNextWorkingRenderApi(RedrawerManager.kt:31)
	at org.jetbrains.skiko.SkiaLayer.init(SkiaLayer.awt.kt:334)
	at org.jetbrains.skiko.SkiaLayer.addNotify(SkiaLayer.awt.kt:161)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at androidx.compose.ui.awt.ComposeWindowPanel.addNotify(ComposeWindowPanel.desktop.kt:147)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:729)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/java.awt.Window.addNotify(Window.java:791)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
	at java.desktop/java.awt.Window.pack(Window.java:829)
	at androidx.compose.ui.util.Windows_desktopKt.setSizeImpl-6HolHcs(Windows.desktop.kt:116)
	at androidx.compose.ui.util.Windows_desktopKt.setSizeSafely-hQcJfNw(Windows.desktop.kt:55)
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Window.desktop.kt:239)
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Window.desktop.kt:176)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:426)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:419)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:78)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:76)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:59)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:55)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2304)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:504)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:260)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke$performUpdate(UpdateEffect.desktop.kt:55)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:64)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:47)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1285)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:982)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1003)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1099)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:631)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:617)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by MatkovIvan** [comment]
Native part is shipped in the separate artifact, so currently Gradle can pick up native part from another version (known issue, but the solution is still under discussion). Please ensure you have updated the dependency for both the common and the current operating system

**Comment by mahozad** [comment]
I really don't know what "native and "common" and "current" refer to!

**Comment by MatkovIvan** [comment]
Compose and Skiko are referenced in your Gradle config twice: in `shared/build.gradle.kts` (common/JVM part) and in `desktopApp/build.gradle.kts` via `compose.desktop.currentOs` (native JNI part compiled for your current system)

See more about this issue here: https://github.com/JetBrains/compose-multiplatform/issues/3282

**Comment by igordmn** [comment]
Let's keep only Compose issue https://github.com/JetBrains/compose-multiplatform/issues/3282. This particular issue is fixable by including 2 artifacts - `skiko-awt` and `skiko-awt-runtime-<platform>`.

Note, that Skiko doesn't support backward compatibility yet (because it is `0.x.x`, and because Skia itself doesn't support backward compatibility). So, it is expected that using an overrided version of Skiko may cause crashes.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-872">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
