### ISSUE TITLE
Crash when using WLToolkit

### ISSUE THREAD

**Issue by DRSchlaubi** [JetBrains/skiko#890]
# Steps to reproduce
- Clone the [awt sample](https://github.com/JetBrains/skiko/tree/master/samples/SkiaAwtSample)
- [Change these two lines to PixelGeometry.UNKNOWN](https://github.com/JetBrains/skiko/blob/master/samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/App.kt#L28-L35)
- Run `./gradlew installDist`
- Run `JAVA_OPTS=-Dawt.toolkit.name.WLToolkit build/install/SkiaAwtSample/bin/SkiaAwtSample`
# Result
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Can't lock DrawingSurface
	at org.jetbrains.skiko.DrawingSurface.lock(AWT.kt:35)
	at org.jetbrains.skiko.AWTKt.useDrawingSurfaceInfo(AWT.kt:94)
	at org.jetbrains.skiko.AWTKt.useDrawingSurfacePlatformInfo(AWT.kt:12)
	at org.jetbrains.skiko.HardwareLayer.init(HardwareLayer.kt:28)
	at org.jetbrains.skiko.SkiaLayer.init(SkiaLayer.awt.kt:332)
	at org.jetbrains.skiko.SkiaLayer.addNotify(SkiaLayer.awt.kt:161)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:721)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/java.awt.Window.addNotify(Window.java:806)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
	at java.desktop/java.awt.Window.pack(Window.java:844)
	at SkiaAwtSample.AppKt.createWindow$lambda$1(App.kt:149)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Runtime used: https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-21.0.2-linux-x64-b375.1.tar.gz

Relates to #28,

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-890">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
