### ISSUE TITLE
Can't publish android target locally when android sdk preview version is installed

### ISSUE THREAD

**Issue by sphrak** [JetBrains/skiko#973]
If I publish android target on my m1 macbook I get an error. But if I run it on a linux system it works. Tried both project's android sdk (via local.properties) and intellij's android sdk, same result. What am I doing wrong? 🤔 

```sh
./gradlew :skiko:publishToMavenLocal \
    -Pdeploy.version=0.8.9.1 \
    -Pskiko.awt.enabled=true \
    -Pskiko.js.enabled=true \
    -Pskiko.wasm.enabled=true \
    -Pskiko.android.enabled=true \
    -Pskiko.native.enabled=true \
    -Pskiko.native.linux.enabled=true \
    -Pskiko.native.mac.enabled=true \
    -Pskiko.native.ios.enabled=true \
    -Pskiko.native.ios.arm64.enabled=true \
    -Pskiko.native.ios.simulatorArm64.enabled=true \
    -Pskiko.native.ios.x64.enabled=true
```

error:
```sh
> Task :skiko:compileKotlinAndroid FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':skiko:compileKotlinAndroid'.
> Could not resolve all files for configuration ':skiko:androidCompileClasspath'.
   > For input string: "VanillaIceCream"
```

Using intellij:
```
IntelliJ IDEA 2024.1.5 (Community Edition)
Build #IC-241.18968.26, built on August 4, 2024
Runtime version: 17.0.11+1-b1207.30 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.plugin.dot.id (1.5.4)
  com.jetbrains.space (241.18968.26)
  Lombook Plugin (241.18034.62)
  org.jetbrains.idea.grammar (2022.3.2)
  com.jetbrains.packagesearch.intellij-plugin (241.0.11)
  org.jetbrains.android (241.17011.79)
  com.squareup.sqldelight (2.0.2)
  androidx.compose.plugins.idea (241.17011.79)
  org.jetbrains.compose.desktop.ide (1.6.2)
  com.suusan2go.kotlin-fill-class (1.0.23)
Kotlin: 241.18968.26-IJ
```

Not sure if relevant, but `androidMain` sources seems detached(?)
![image](https://github.com/user-attachments/assets/5a978186-180d-48f2-a1f5-245b5c7cb7fa)

**Comment by sphrak** [comment]
The actual crash is:

```
java.lang.NumberFormatException: For input string: "VanillaIceCream"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at tasks.configuration.JvmTasksConfigurationKt$androidJar$1.transform(JvmTasksConfiguration.kt:544)
	at tasks.configuration.JvmTasksConfigurationKt$androidJar$1.transform(JvmTasksConfiguration.kt:538)
	at org.gradle.api.internal.provider.ValueSupplier$Present.transform(ValueSupplier.java:511)
	at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:91)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
	at org.gradle.api.internal.provider.ProviderResolutionStrategy$2.resolve(ProviderResolutionStrategy.java:33)
	at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitChildren(ProviderBackedFileCollection.java:64)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:113)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:113)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:77)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:594)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitChildren(DefaultConfigurableFileCollection.java:416)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:113)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:124)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-973">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
