### ISSUE TITLE
Cannot differentiate awt and android targets with attributes

### ISSUE THREAD

**Issue by owengray-google** [JetBrains/skiko#987]
I am getting an error like this when trying to resolve `org.jetbrains.skiko:skiko` for a KMP desktop target:
```
Caused by: org.gradle.internal.component.resolution.failure.exception.VariantSelectionByAttributesException: Cannot choose between the available variants of org.jetbrains.skiko:skiko:0.7.7:
  - androidRuntimeElements-published
  - awtRuntimeElements-published
All of them match the consumer attributes:
  - Variant 'androidRuntimeElements-published' capability 'org.jetbrains.skiko:skiko:0.7.7':
      - Unmatched attributes:
          - Provides org.gradle.category 'library' but the consumer didn't ask for it
          - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
          - Provides org.gradle.status 'release' but the consumer didn't ask for it
          - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Provides org.jetbrains.kotlin.platform.type 'jvm' but the consumer didn't ask for it
          - Provides ui 'android' but the consumer didn't ask for it
  - Variant 'awtRuntimeElements-published' capability 'org.jetbrains.skiko:skiko:0.7.7':
      - Unmatched attributes:
          - Provides org.gradle.category 'library' but the consumer didn't ask for it
          - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
          - Provides org.gradle.status 'release' but the consumer didn't ask for it
          - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Provides org.jetbrains.kotlin.platform.type 'jvm' but the consumer didn't ask for it
    at androidx.build.CheckKotlinApiTargetTask.<init>(CheckKotlinApiTargetTask.kt:46)
    at androidx.build.CheckKotlinApiTargetTask_Decorated.<init>(Unknown Source)
```

Looking at your [published .module file](https://repo1.maven.org/maven2/org/jetbrains/skiko/skiko/0.8.11/skiko-0.8.11.module), indeed the only attribute difference between those two variants is that `android` has an extra attribute. However, gradle does not allow you to perform exclude-based matching, so this doesn't help you resolve a variant for a desktop/awt target.

**Comment by eymar** [comment]
I guess the dependency was declared as "org.jetbrains.skiko:skiko"?

Here is an example how it's declared in some of the examples: https://github.com/JetBrains/skiko/blob/70282bd65e4b362db419ac787bece2ab6bd41974/samples/SkiaAwtSample/build.gradle.kts#L41 or here https://github.com/JetBrains/skiko/blob/45c1a7df474ce1e2df44c00505d5d497d0fed70a/samples/SkiaMultiplatformSample/build.gradle.kts#L144

The gradle module metadata has an issue indeed. For the time being the publication of skiko android variant was disabled, although for a different reason (https://github.com/JetBrains/skiko/issues/761#issuecomment-2329080310)

The proper solution was put to backlog: https://youtrack.jetbrains.com/issue/CMP-6640

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-987">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
